{
 "title": "Mastodon: Sidekiq Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(sidekiq_processes,env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Enqueuing rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sidekiq_enqueued_jobs{env=\"$env\"}[1m])"
    }
   ]
  },
  {
   "title": "Processing rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sidekiq_processed_jobs_total{env=\"$env\"}[1m])"
    }
   ]
  },
  {
   "title": "Failed growth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(sidekiq_failed_jobs_total{env=\"$env\"}[1m])"
    }
   ]
  },
  {
   "title": "Retry jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sidekiq_retry_jobs{env=\"$env\"}[1m])"
    }
   ]
  },
  {
   "title": "Dead jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sidekiq_dead_jobs{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Enqueued jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sidekiq_enqueued_jobs{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Busy workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sidekiq_busy_workers{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Scheduled jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sidekiq_scheduled_jobs{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Queues latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(sidekiq_queue_latency_seconds{env=\"$env\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue enqueued jobs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sidekiq_queue_enqueued_jobs{env=\"$env\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Retry Jobs over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sidekiq_retry_jobs{env=\"$env\"}",
     "legendFormat": "retry jobs"
    }
   ]
  },
  {
   "title": "Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "rate(sidekiq_processed_jobs_total{env=\"$env\"}[1m])",
     "legendFormat": "processing rate"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Processed Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sidekiq_processed_jobs_total{env=\"$env\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enqueued Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 4, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidekiq_queue_enqueued_jobs{env=\"$env\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Enqueued Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sidekiq_queue_enqueued_jobs{env=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(sidekiq_failed_jobs_total{env=\"$env\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busy Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 4, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidekiq_queue_busy_workers{env=\"$env\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Busy workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sidekiq_busy_workers{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Retry Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidekiq_retry_jobs{env=\"$env\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidekiq_queue_latency_seconds{env=\"$env\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sidekiq_queue_latency_seconds{env=\"$env\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processes & Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Processes per Host",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidekiq_host_processes{env=\"$env\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Sidekiq Processes",
   "type": "stat",
   "description": "This is the number of processes, mailer and scheduler should always be 1",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidekiq_queue_processes{env=\"$env\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "# of Sidekiq Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sidekiq_queue_processes{env=\"$env\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Sidekiq Workers",
   "type": "stat",
   "description": "This is the number of workers, not the number of queue listeners",
   "gridPos": { "h": 5, "w": 16, "x": 4, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sidekiq_queue_workers{env=\"$env\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "# of Sidekiq Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sidekiq_queue_workers{env=\"$env\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}